//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Boolmaster_Samodin.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookAuthor
    {
        public BookAuthor()
        {
            this.Circulation = new HashSet<Circulation>();
        }
    
        public int BookAuthorId { get; set; }
        public int Bookid { get; set; }
        public int Authorid { get; set; }
    
        public virtual Authors Authors { get; set; }
        public virtual Book Book { get; set; }
        public virtual ICollection<Circulation> Circulation { get; set; }
    }
}
