//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Boolmaster_Samodin.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Circulation
    {
        public int CirculationId { get; set; }
        public int BookAuthorId { get; set; }
        public int CustomerId { get; set; }
        public System.DateTime IssueDate { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public bool IsReturned { get; set; }
    
        public virtual BookAuthor BookAuthor { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
